#!/usr/bin/expect
set dbname [lindex $argv 0]
set password [lindex $argv 1]

spawn $env(SHELL)
send "cd scripts\r"
expect "scripts"
send "/opt/PostgreSQL/9.1/bin/psql -U postgres -d $dbname < clear-db.sql\r"
expect "Password for user postgres:"
send "$password\r"
expect "testsuite"
send "/opt/PostgreSQL/9.1/bin/psql -U postgres -d $dbname < backup.sql\r"
expect "Password for user postgres:"
send "$password\r"
expect eof
